
local harpoon = require("harpoon")
vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end)
vim.keymap.set("n", "<leader>Hb", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<A-q>", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<A-w>", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<A-e>", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<A-r>", function()
	harpoon:list():select(4)
end)
--		vim.keymap.set("n", "<C-S-P>", function() harpoon:list():prev() end)
--		vim.keymap.set("n", "<C-S-N>", function() harpoon:list():next() end)
